# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
